### PR TITLE
large "open next feed" button, color changes

### PR DESCRIPTION
**Pull request by wolfgangasdf**
Hi, awesome theme, thanks! Here a pull request to make the "open next feed" button big. I also added things to make things here (on mac/Chrome, latest version) nicer like gray scrollbars and gray line under the title. Please reject the pull request if you don't think it fits!

### CODE REVIEW

**Comment by Gravemind** [comment]
Thank You. I split your commit and "cherry-picked" the changes I liked.

As for the other changes, I'm not sure:

- I don't like link and accent color same as fg: it makes a lot of text blend-in instead of standing out: bad for links, but also in menus, preferences etc... (If you really want it, you can [customize `local.less`](https://github.com/Gravemind/tt-rss-feedlish-theme#customize) and rebuild)

- For "next unread feed" `#headlines-spacer a`:
  - `height: 100%;` doesn't change anything ? maybe `padding: 32px 0 32px 0;` ?
  - I couldn't find what `\A \A` does ?

**Comment by wolfgangasdf** [comment]
1st: Sure, I just wanted to get rid of all blue things. 
2nd point: This makes the (IMO unnecessarily) small "open next feed" href become as big as the parent div (the empty space below articles, like feedly if I remember correctly), you can click everywhere! This was the main motivation of my changes. The \a stuff is an ugly hack to move the link text "open next feed" down, because otherwise, it scrolls out of view if completely scrolled down (useful if 'mark read on scroll').

**Comment by Gravemind** [comment]
Ok, got it: I hadn't tried the "mark as read on scroll" mode.

I added the `height: 100%` only when "mark as read on scroll" (`.auto_catchup`), does that work for you ?

**Comment by wolfgangasdf** [comment]
Sorry for the late reply, thanks a lot for cleaning up my mess, this works very nicely!
Not relevant: I think the `a:hover { background: @feedlish-headline-hover-bg; }` is very nice also with auto_catchup, it could go in `#headlines-spacer` above (same with `a { padding: 20px 0 20px 0; }`, doesn't hurt).

**Pull request closed without merging**
